# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start_window(object):
    def setupUi(self, start_window):
        start_window.setObjectName("start_window")
        start_window.resize(538, 608)
        font = QtGui.QFont()
        font.setPointSize(8)
        start_window.setFont(font)
        start_window.setStyleSheet("background-color: #3D3D3D;\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(start_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_for_Box_choice = QtWidgets.QLabel(start_window)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_for_Box_choice.setFont(font)
        self.text_for_Box_choice.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"")
        self.text_for_Box_choice.setObjectName("text_for_Box_choice")
        self.horizontalLayout.addWidget(self.text_for_Box_choice)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Box_choice = QtWidgets.QComboBox(start_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box_choice.sizePolicy().hasHeightForWidth())
        self.Box_choice.setSizePolicy(sizePolicy)
        self.Box_choice.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_choice.setFont(font)
        self.Box_choice.setStyleSheet("border: 2px solid #A4004D; \n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: #b80000;\n"
"\n"
"\n"
"")
        self.Box_choice.setObjectName("Box_choice")
        self.horizontalLayout.addWidget(self.Box_choice)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_directory = QtWidgets.QLineEdit(start_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_directory.setFont(font)
        self.line_directory.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_directory.setObjectName("line_directory")
        self.horizontalLayout_2.addWidget(self.line_directory)
        self.Button_directory = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_directory.setFont(font)
        self.Button_directory.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_directory.setObjectName("Button_directory")
        self.horizontalLayout_2.addWidget(self.Button_directory)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_verify = QtWidgets.QLineEdit(start_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_verify.setFont(font)
        self.line_verify.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_verify.setObjectName("line_verify")
        self.verticalLayout.addWidget(self.line_verify)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.text_for_line_symbol = QtWidgets.QLabel(start_window)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_for_line_symbol.setFont(font)
        self.text_for_line_symbol.setStyleSheet("background-color: #404040;\n"
"color: white;")
        self.text_for_line_symbol.setObjectName("text_for_line_symbol")
        self.verticalLayout.addWidget(self.text_for_line_symbol)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_symbol = QtWidgets.QLineEdit(start_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_symbol.setFont(font)
        self.line_symbol.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_symbol.setObjectName("line_symbol")
        self.horizontalLayout_3.addWidget(self.line_symbol)
        self.Button_symbol = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_symbol.setFont(font)
        self.Button_symbol.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_symbol.setObjectName("Button_symbol")
        self.horizontalLayout_3.addWidget(self.Button_symbol)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.text_line_example = QtWidgets.QLabel(start_window)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_line_example.setFont(font)
        self.text_line_example.setStyleSheet("background-color: #404040;\n"
"color: white;")
        self.text_line_example.setObjectName("text_line_example")
        self.verticalLayout.addWidget(self.text_line_example)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_example = QtWidgets.QLineEdit(start_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_example.setFont(font)
        self.line_example.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_example.setObjectName("line_example")
        self.gridLayout.addWidget(self.line_example, 1, 2, 1, 3)
        self.Button_cut = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_cut.setFont(font)
        self.Button_cut.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_cut.setObjectName("Button_cut")
        self.gridLayout.addWidget(self.Button_cut, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 4, 1, 1)
        self.label_links = QtWidgets.QLabel(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_links.setFont(font)
        self.label_links.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.label_links.setObjectName("label_links")
        self.gridLayout.addWidget(self.label_links, 0, 0, 1, 2)
        self.label_rechts = QtWidgets.QLabel(start_window)
        self.label_rechts.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_rechts.setFont(font)
        self.label_rechts.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.label_rechts.setObjectName("label_rechts")
        self.gridLayout.addWidget(self.label_rechts, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.links_int = QtWidgets.QSpinBox(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.links_int.setFont(font)
        self.links_int.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.links_int.setObjectName("links_int")
        self.gridLayout.addWidget(self.links_int, 1, 0, 1, 2)
        self.rechts_int = QtWidgets.QSpinBox(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rechts_int.setFont(font)
        self.rechts_int.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.rechts_int.setObjectName("rechts_int")
        self.gridLayout.addWidget(self.rechts_int, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.Button_start = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Button_start.setFont(font)
        self.Button_start.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_start.setObjectName("Button_start")
        self.horizontalLayout_5.addWidget(self.Button_start)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.text_results = QtWidgets.QTextEdit(start_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_results.setFont(font)
        self.text_results.setStyleSheet("border: 2px solid #A4004D;\n"
"color: rgb(255, 255, 255);\n"
"background-color:  #404040;")
        self.text_results.setDocumentTitle("")
        self.text_results.setObjectName("text_results")
        self.verticalLayout.addWidget(self.text_results)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.Button_clear = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_clear.setFont(font)
        self.Button_clear.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_clear.setObjectName("Button_clear")
        self.horizontalLayout_4.addWidget(self.Button_clear)
        self.Button_undo = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_undo.setFont(font)
        self.Button_undo.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_undo.setObjectName("Button_undo")
        self.horizontalLayout_4.addWidget(self.Button_undo)
        self.Button_save_to_file = QtWidgets.QPushButton(start_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_save_to_file.setFont(font)
        self.Button_save_to_file.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_save_to_file.setObjectName("Button_save_to_file")
        self.horizontalLayout_4.addWidget(self.Button_save_to_file)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(start_window)
        QtCore.QMetaObject.connectSlotsByName(start_window)

    def retranslateUi(self, start_window):
        _translate = QtCore.QCoreApplication.translate
        start_window.setWindowTitle(_translate("start_window", "Check int number"))
        self.text_for_Box_choice.setText(_translate("start_window", "Was wollen Sie untersuchen?"))
        self.line_directory.setPlaceholderText(_translate("start_window", "Wählen Sie ein Ordner aus"))
        self.Button_directory.setText(_translate("start_window", "   Open   "))
        self.line_verify.setPlaceholderText(_translate("start_window", "Ein Beispiel der Datei, die verifiziert wird"))
        self.text_for_line_symbol.setText(_translate("start_window", "Orner oder Dateien nur mit folgenden Symbolen untersuchen."))
        self.line_symbol.setPlaceholderText(_translate("start_window", "Zum Beispiel: .zip"))
        self.Button_symbol.setText(_translate("start_window", "     Anwenden    "))
        self.text_line_example.setText(_translate("start_window", "Ignorirere folgende anzahl der Buchstaben:"))
        self.line_example.setPlaceholderText(_translate("start_window", "A file example that will be verifying"))
        self.Button_cut.setText(_translate("start_window", "  Links/Rechts ausrechnen  "))
        self.label_links.setText(_translate("start_window", "  Links   "))
        self.label_rechts.setText(_translate("start_window", "  Rechts  "))
        self.Button_start.setText(_translate("start_window", "                Start                "))
        self.text_results.setPlaceholderText(_translate("start_window", "Alle Ergebnisse werden hier und im Terminal angezeigt"))
        self.Button_clear.setText(_translate("start_window", "  Clear  "))
        self.Button_undo.setText(_translate("start_window", "  Undo  "))
        self.Button_save_to_file.setText(_translate("start_window", "  Save to File  "))
