# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 607)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        Form.setStyleSheet("background-color: #3D3D3D;\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Box_chois = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box_chois.sizePolicy().hasHeightForWidth())
        self.Box_chois.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_chois.setFont(font)
        self.Box_chois.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"color: white;\n"
"border: 2px solid #A4004D;\n"
"\n"
"\n"
"")
        self.Box_chois.setObjectName("Box_chois")
        self.horizontalLayout.addWidget(self.Box_chois)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_directory = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_directory.setFont(font)
        self.line_directory.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_directory.setObjectName("line_directory")
        self.horizontalLayout_2.addWidget(self.line_directory)
        self.Button_directory = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_directory.setFont(font)
        self.Button_directory.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_directory.setObjectName("Button_directory")
        self.horizontalLayout_2.addWidget(self.Button_directory)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_verify = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_verify.setFont(font)
        self.line_verify.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_verify.setObjectName("line_verify")
        self.verticalLayout.addWidget(self.line_verify)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #404040;\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_symbol = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_symbol.setFont(font)
        self.line_symbol.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_symbol.setObjectName("line_symbol")
        self.horizontalLayout_3.addWidget(self.line_symbol)
        self.Button_symbol = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_symbol.setFont(font)
        self.Button_symbol.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_symbol.setObjectName("Button_symbol")
        self.horizontalLayout_3.addWidget(self.Button_symbol)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: #404040;\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_example = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_example.setFont(font)
        self.line_example.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.line_example.setObjectName("line_example")
        self.gridLayout.addWidget(self.line_example, 1, 2, 1, 3)
        self.Button_cut = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_cut.setFont(font)
        self.Button_cut.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_cut.setObjectName("Button_cut")
        self.gridLayout.addWidget(self.Button_cut, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.links_int = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.links_int.setFont(font)
        self.links_int.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.links_int.setObjectName("links_int")
        self.gridLayout.addWidget(self.links_int, 1, 0, 1, 2)
        self.rechts_int = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rechts_int.setFont(font)
        self.rechts_int.setStyleSheet("background-color: #404040;\n"
"color: white;\n"
"border: 2px solid #A4004D;")
        self.rechts_int.setObjectName("rechts_int")
        self.gridLayout.addWidget(self.rechts_int, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.button_start = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_5.addWidget(self.button_start)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.text_results = QtWidgets.QTextEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_results.setFont(font)
        self.text_results.setStyleSheet("border: 2px solid #A4004D;\n"
"color: rgb(255, 255, 255);\n"
"background-color:  #404040;")
        self.text_results.setDocumentTitle("")
        self.text_results.setObjectName("text_results")
        self.verticalLayout.addWidget(self.text_results)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.Button_clear = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_clear.setFont(font)
        self.Button_clear.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_clear.setObjectName("Button_clear")
        self.horizontalLayout_4.addWidget(self.Button_clear)
        self.Button_undo = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_undo.setFont(font)
        self.Button_undo.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_undo.setObjectName("Button_undo")
        self.horizontalLayout_4.addWidget(self.Button_undo)
        self.Button_save_to_file = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_save_to_file.setFont(font)
        self.Button_save_to_file.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.Button_save_to_file.setObjectName("Button_save_to_file")
        self.horizontalLayout_4.addWidget(self.Button_save_to_file)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Analysis Ganzzahlige Nummerierung"))
        self.label.setText(_translate("Form", "Was wollen Sie untersuchen?"))
        self.line_directory.setPlaceholderText(_translate("Form", "Wählen Sie ein Ordner aus"))
        self.Button_directory.setText(_translate("Form", "   Open   "))
        self.line_verify.setPlaceholderText(_translate("Form", "Ein Beispiel der Datei, die verifiziert wird"))
        self.label_3.setText(_translate("Form", "Orner oder Dateien nur mit folgenden Symbolen untersuchen."))
        self.line_symbol.setPlaceholderText(_translate("Form", "Zum Beispiel: .zip"))
        self.Button_symbol.setText(_translate("Form", "     Anwenden    "))
        self.label_4.setText(_translate("Form", "Ignorirere folgende anzahl der Buchstaben:"))
        self.line_example.setPlaceholderText(_translate("Form", "A file example that will be verifying"))
        self.Button_cut.setText(_translate("Form", "  Links/Rechts ausrechnen  "))
        self.label_2.setText(_translate("Form", "  Links   "))
        self.label_5.setText(_translate("Form", "  Rechts  "))
        self.button_start.setText(_translate("Form", "                Start                "))
        self.text_results.setPlaceholderText(_translate("Form", "Alle Ergebnisse werden hier und im Terminal angezeigt"))
        self.Button_clear.setText(_translate("Form", "  Clear  "))
        self.Button_undo.setText(_translate("Form", "  Undo  "))
        self.Button_save_to_file.setText(_translate("Form", "  Save to File  "))
